hob: {
  inherit (hob)
    astronauta-nvim
    barbar-nvim
    beacon-nvim
    bufferize-vim
    BufOnly-nvim
    completion-nvim
    completion-buffers
    dwm-vim
    express_line-nvim
    formatter-nvim
    FTerm-nvim
    fzf-lsp-nvim
    fzf-vim
    galaxyline-nvim
    gina-vim
    gitsigns-nvim
    guile-vim
    hop-nvim
    kommentary
    lspsaga-nvim
    lsp-status-nvim
    nvim-autopairs
    nvim-base16-lua
    nvim-bufferline-lua
    nvim-colorizer-lua
    nvim-cursorline
    nvim-fzf
    nvim-fzf-commands
    nvim-lazygit
    nvim-lspconfig
    nvim-lspfuzzy
    nvim-treesitter
    nvim-treesitter-context
    nvim-treesitter-refactor
    nvim-treesitter-textobjects
    nvim-tree-lua
    nvim-web-devicons
    lir-nvim
    neogit
    plenary-nvim
    popup-nvim
    ron-vim
    telescope-nvim
    tokei-vim
    vim-shen
    vim-visual-multi
    zoxide-vim;
}
