# Disable annoying globbing
unsetopt nomatch

autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic
autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic

# auto cd
setopt AUTO_CD
